# Development environment configuration
# This file overrides settings in _config.yml for the dev branch deployment

# GitHub Pages default URL for the repository
url: https://cepro.github.io
baseurl: /www.waterlilies.energy-jekyll

# Development environment indicator
environment: development