# Development environment configuration
# This file overrides settings in _config.yml for the dev branch deployment on Fly.io

# Fly.io dev deployment URL
url: https://waterlilies-dev.fly.dev
baseurl: ""

# Development environment indicator
environment: development