# fly.toml app configuration file generated for waterlilies-dev on 2025-09-08T09:55:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'waterlilies-dev'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  count = 1
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
